CREATE TABLE users(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE profit(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    costs FLOAT(10,6) NOT NULL,
    earnings FLOAT(10,6) NOT NULL,
    date VARCHAR(255) NOT NULL,
    user VARCHAR(255) NOT NULL
);

CREATE TABLE location(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    lat FLOAT(10,6) NOT NULL,
    lng FLOAT(10,6) NOT NULL,
    user VARCHAR(255) NOT NULL
);

CREATE TABLE form(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    number_empl INT(255) NOT NULL,
    salary BIGINT(255) NOT NULL,
    user VARCHAR(255) NOT NULL
);

CREATE TABLE events(
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start_event DATETIME NOT NULL,
    end_event DATETIME NOT NULL,
    user VARCHAR(255) NOT NULL
);